import { COLORS } from "../../constants/colors";

export const TOKENS = {
  colors: {
    background: COLORS.background,
    surface: COLORS.white,
    primary: COLORS.primary,
    text: "#221f1b",
    textMuted: "#7c726b",
    textSoft: "#999999",
    border: "#d9d9d9",
    borderSoft: "#ebe4dd",
    chipBg: "#f7e8ec",
    chipText: COLORS.primary,
    warningBg: "#fff4e7",
    warningBorder: "#f2d7ab",
    warningText: "#946c20",
    introBg: "#f7e8ec",
    introLabel: "#9d6a75",
    introText: "#7d6d70",
    neutralButtonBg: "#f4f4f4",
    neutralButtonBorder: "#d7d7d7",
    neutralButtonText: "#666666",
    lockedBg: "#f9fafc",
    dangerBg: "#fff7f7",
    dangerBorder: "#f0c9c9",
    dangerText: "#d83030",
  },
  spacing: {
    screen: 20,
    section: 18,
    field: 16,
    row: 14,
    chip: 8,
    headerTop: 10,
    headerBottom: 22,
    contentBottom: 32,
  },
  radius: {
    field: 18,
    card: 22,
    chip: 16,
    banner: 16,
  },
  sizes: {
    controlHeight: 62,
    textAreaHeight: 120,
    avatar: 58,
    avatarSmall: 52,
  },
  type: {
    title: 28,
    section: 16,
    body: 16,
    bodyLarge: 17,
    helper: 13,
  },
  shadow: {
    card: {
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
  },
} as const;
