import { StyleSheet } from "react-native";

import { COLORS } from "../../../constants/colors";
import { PATTERNS } from "../../styles/patterns";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  container: {
    paddingBottom: 112,
  },
  heroHeader: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  heroHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 12,
  },
  stickyHeader: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
    marginBottom: 8,
    zIndex: 20,
  },
  welcome: {
    color: "#f5c5ce",
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 2,
  },
  userName: {
    color: "#fff",
    fontSize: 26,
    fontWeight: "800",
  },
  headerAction: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  searchBarCompact: {
    flex: 1,
    minWidth: 0,
    minHeight: 56,
    backgroundColor: COLORS.white,
    borderRadius: 18,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    ...PATTERNS.surfaces.cardSection,
    marginHorizontal: 0,
    marginBottom: 0,
    paddingVertical: 0,
  },
  searchText: {
    flex: 1,
    flexShrink: 1,
    color: "#9a9a9a",
    fontSize: 15,
    fontWeight: "500",
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 2,
  },
  sectionTitle: {
    color: "#8a8a8a",
    fontSize: 14,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 12,
    marginTop: 6,
  },
  nextAppointmentCard: {
    backgroundColor: COLORS.white,
    borderRadius: 22,
    padding: 18,
    marginBottom: 16,
    ...PATTERNS.surfaces.cardSection,
    marginHorizontal: 0,
  },
  nextAppointmentTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  nextAppointmentTimeBox: {
    flex: 1,
  },
  nextAppointmentTime: {
    color: COLORS.primary,
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 6,
  },
  nextAppointmentDate: {
    color: "#6f6f6f",
    fontSize: 14,
    textTransform: "capitalize",
  },
  nextAppointmentDivider: {
    height: 1,
    backgroundColor: "#ece7e2",
    marginVertical: 16,
  },
  nextAppointmentEyebrow: {
    color: "#9a9a9a",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  nextAppointmentTitle: {
    color: "#1f1a16",
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 6,
  },
  nextAppointmentMeta: {
    color: "#6d625b",
    fontSize: 14,
    lineHeight: 20,
  },
  nextAppointmentActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 16,
  },
  nextAppointmentLink: {
    color: COLORS.primary,
    fontSize: 15,
    fontWeight: "800",
  },
  nextStatusChip: {
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  nextStatusChipSuccess: {
    backgroundColor: "#e6f3e8",
  },
  nextStatusChipWarning: {
    backgroundColor: "#fff4db",
  },
  nextStatusChipDanger: {
    backgroundColor: "#fdeaea",
  },
  nextStatusChipMuted: {
    backgroundColor: "#ececec",
  },
  nextStatusText: {
    fontSize: 13,
    fontWeight: "800",
  },
  nextStatusTextSuccess: {
    color: "#2f8c3c",
  },
  nextStatusTextWarning: {
    color: "#b98500",
  },
  nextStatusTextDanger: {
    color: "#d32f2f",
  },
  nextStatusTextMuted: {
    color: "#444444",
  },
  primaryManagementCard: {
    backgroundColor: COLORS.primary,
    borderRadius: 20,
    minHeight: 102,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  secondaryManagementCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    minHeight: 102,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  primaryManagementIcon: {
    width: 58,
    height: 58,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.16)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  secondaryManagementIcon: {
    width: 58,
    height: 58,
    borderRadius: 16,
    backgroundColor: "#f7e8ec",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  managementTextBox: {
    flex: 1,
  },
  primaryManagementTitle: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 4,
  },
  secondaryManagementTitle: {
    color: "#111",
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 4,
  },
  primaryManagementSubtitle: {
    color: "#ffd3db",
    fontSize: 13,
    lineHeight: 18,
  },
  secondaryManagementSubtitle: {
    color: "#8d8d8d",
    fontSize: 13,
    lineHeight: 18,
  },
  quickGrid: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  quickCard: {
    flex: 1,
    minHeight: 118,
    backgroundColor: "#fff",
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  quickCardTitle: {
    color: "#111",
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 10,
    lineHeight: 18,
  },
  utilitySummaryRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 10,
  },
  utilitySummaryCard: {
    flex: 1,
    minHeight: 110,
    backgroundColor: "#fff",
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    padding: 14,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  utilitySummarySingleCard: {
    minHeight: 104,
    backgroundColor: "#fff",
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    padding: 14,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  utilitySummaryLabel: {
    color: "#b2b2b2",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
    textAlign: "center",
  },
  utilitySummaryValue: {
    color: COLORS.primary,
    fontSize: 24,
    fontWeight: "800",
    textAlign: "center",
  },
  utilitySummaryDay: {
    color: "#8f8f8f",
    fontSize: 13,
    fontWeight: "500",
    marginTop: 8,
    textTransform: "capitalize",
  },
  fabMenu: {
    position: "absolute",
    right: 20,
    bottom: 112,
    gap: 16,
    alignItems: "flex-end",
  },
  fabMenuButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    shadowColor: COLORS.primaryDark,
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  fabMenuText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 30,
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: COLORS.primary,
    borderWidth: 3,
    borderColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.primaryDark,
    shadowOpacity: 0.35,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 9,
  },
});
